### ISSUE TITLE
Tracy-0.9 GUI fails to build on Linux xubuntu-18.04.6

### ISSUE THREAD

**Issue by dpelle** [wolfpld/tracy#484]
Tracy-0.9 GUI fails to build on Linux xubuntu-18.04.6.

Tracy-0.8.2 GUI was building fine.
This is the error I get with Tracy-0.9:

```
$ cd tracy/profiler/build/unix
$ git checkout v0.9
$ PATH=/usr/local/bin:/usr/bin:/bin CC=clang-14 CXX=clang++-14 make
...snip...
clang++-14 -c -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/capstone -I../../../imgui -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -O3 -flto -march=native  -std=c++17 -DNDEBUG -DIMGUI_ENABLE_FREETYPE ../../../server/TracySourceView.cpp -o obj/release/o/o/o/../../../server/TracySourceView.o
../../../server/TracySourceView.cpp:736:46: error: use of undeclared identifier 'CS_GRP_BRANCH_RELATIVE'
                else if( detail.groups[j] == CS_GRP_BRANCH_RELATIVE && opType < OpType::Branch ) opType = OpType::Branch;
                                             ^
../../../server/TracySourceView.cpp:739:46: error: use of undeclared identifier 'CS_GRP_PRIVILEGE'
                else if( detail.groups[j] == CS_GRP_PRIVILEGE && opType < OpType::Privileged )
                                             ^
2 errors generated.
../../../common/unix.mk:30: recipe for target 'obj/release/o/o/o/../../../server/TracySourceView.o' failed
make[1]: *** [obj/release/o/o/o/../../../server/TracySourceView.o] Error 1
make[1]: Leaving directory '/home/dope/sb/tracy/profiler/build/unix'
Makefile:7: recipe for target 'release' failed
make: *** [release] Error 2
```

It looks like /usr/include/capstone/ is too old on xubuntu-18.04.6.

It's not really a Tracy bug, but perhaps CS_GRP_PRIVILEGE can be made optional in Tracy 
to be able to build on older Ubuntu distributions?

**Comment by gedalia** [comment]
You can download and install a newer version of capstone and it will compile.

**Comment by dpelle** [comment]
@gedalia wrote:
> You can download and install a newer version of capstone and it will compile.

Right.  For reference, I did:
```
$ sudo apt-get remove libcapstone-dev  libcapstone3
$ git clone https://github.com/libcapstone/libcapstone.git
$ cd libcapstone
$ PATH=/usr/local/bin:/usr/bin:/bin CC=clang-15 CXX=clang++-15 make -j12
$ sudo make install
```

And then I could build tracy-0.9:
```
$ cd tracy/profiler/build/unix
$ PATH=/usr/local/bin:/usr/bin:/bin CC=clang-15 CXX=clang++-15 make -j12 debug
```

**Comment by wolfpld** [comment]
Closing, as you have found a solution.

Generally speaking, support for 7-year-old libraries is not something I'm interested in.

https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libcapstone-dev_3.0.4-5_amd64.deb.html
https://www.capstone-engine.org/Version-3.0.4
