### ISSUE TITLE
Compile error: unknown type name 'CONTROLTRACE_ID' on Windows + VS2022 Clang (works on v0.13.0)

### ISSUE THREAD

**Issue by xuxmin** [wolfpld/tracy#1243]
I encountered a compilation error when building the latest version of Tracy on Windows with Visual Studio 2022 + Clang toolchain. 
The error message is:
```
[build] D:\Project\Code\RenderEngine\engine\3rdparty\tracy\public\client\windows/TracyETW.cpp(25,5): error: unknown type name 'CONTROLTRACE_ID'
[build]    25 |     CONTROLTRACE_ID handle = 0;
[build] D:\Project\Code\RenderEngine\engine\3rdparty\tracy\public\client\windows/TracyETW.cpp(517,8): error: unknown type name 'PROCESSTRACE_HANDLE'
[build]   517 | static PROCESSTRACE_HANDLE SetupEventConsumer( const Session& session, PEVENT_RECORD_CALLBACK callback )
[build]       |        ^
[build] D:\Project\Code\RenderEngine\engine\3rdparty\tracy\public\client\windows/TracyETW.cpp(527,5): error: unknown type name 'PROCESSTRACE_HANDLE'
[build]   527 |     PROCESSTRACE_HANDLE hConsumer = OpenTraceA( &trace );
[build]       |     ^
[build] D:\Project\Code\RenderEngine\engine\3rdparty\tracy\public\client\windows/TracyETW.cpp(534,33): error: unknown type name 'PROCESSTRACE_HANDLE'
[build]   534 | static ULONG StopEventConsumer( PROCESSTRACE_HANDLE hEventConsumer )
[build]       |                                 ^
[build] D:\Project\Code\RenderEngine\engine\3rdparty\tracy\public\client\windows/TracyETW.cpp(542,33): error: unknown type name 'PROCESSTRACE_HANDLE'
[build]   542 | static ULONG EventConsumerLoop( PROCESSTRACE_HANDLE hEventConsumer )
[build]       |                                 ^
[build] In file included from D:\Project\Code\RenderEngine\engine\3rdparty\tracy\public\TracyClient.cpp:27:
[build] D:\Project\Code\RenderEngine\engine\3rdparty\tracy\public\client/TracySysTrace.cpp(181,8): error: unknown type name 'PROCESSTRACE_HANDLE'
[build]   181 | static PROCESSTRACE_HANDLE consumer_kernel = INVALID_PROCESSTRACE_HANDLE;
[build]       |        ^
[build] D:\Project\Code\RenderEngine\engine\3rdparty\tracy\public\client/TracySysTrace.cpp(182,8): error: unknown type name 'PROCESSTRACE_HANDLE'
[build]   182 | static PROCESSTRACE_HANDLE consumer_vsync = INVALID_PROCESSTRACE_HANDLE;
```
The tag version v0.13.0 compiles successfully in the exact same environment.

**Comment by Lectem** [comment]
What version of the windows SDK are you using?
It's as of you were using a very old one (or corrupted one?) since `evntrace.h` should contain all the types mentionned in your errors (`CONTROLTRACE_ID` and `PROCESSTRACE_HANDLE`).

Please check what `evntrace.h` file is included?

**Comment by Kaltxi** [comment]
So I've looked at my version of `evntrace.h` (from SDK 10.0.22621), and it indeed lacks these types, instead they are:
```
CONTROLTRACE_ID     -> TRACEHANDLE
PROCESSTRACE_HANDLE -> TRACEHANDLE
```

So I just patched `TracyETW.cpp` and `TracySysTrace.cpp`. But it's probably best to handle the API changes more graciously.

Also, specifically integrating tracy into and old UE4 I had to fix some printf errors due to using `%u` and `%x` insread of `%lu` and `%lx` for `ULONG`.

**Comment by Brainzman** [comment]
Small note, and for reference for people running into this in the future, we ran into this while integrating Tracy in Blender. Patch fix was simple enough ([link](https://projects.blender.org/blender/blender/commit/034ae551697bc973ae9067af6ffb401ae02a8eca)). In our case we stick with 22621 as even though it's EOS, it's also the [VFX Reference Platform](https://vfxplatform.com) minimum SDK, and we thus use it as a baseline (at least for now, we might upgrade it in the future).
