### ISSUE TITLE
Build errors on Debian Trixie

### ISSUE THREAD

**Issue by pfirsich** [wolfpld/tracy#1311]
Hey! I am trying to build the server and I get the following build errors:

```
/home/joel/repos/tracy/profiler/src/BackendWayland.cpp: In member function ‘void Backend::Run()’:
/home/joel/repos/tracy/profiler/src/BackendWayland.cpp:1138:25: error: ‘wl_display_dispatch_timeout’ was not declared in this scope; did you mean ‘wl_display_dispatch_queue’?
 1138 |     while( s_running && wl_display_dispatch_timeout( s_dpy, &zero ) != -1 )
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         wl_display_dispatch_queue

```
My version of libwayland-client is:
```
$ apt-cache show libwayland-client0 | grep Version
Version: 1.23.1-3
```
I am on Debian Trixie:
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 13 (trixie)"
NAME="Debian GNU/Linux"
VERSION_ID="13"
VERSION="13 (trixie)"
VERSION_CODENAME=trixie
DEBIAN_VERSION_FULL=13.4
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I think the version on Debian Trixie might be too old (1.24 introduces that function - see here [wayland-devel](https://lore.freedesktop.org/wayland-devel/plU5smxin5VXbiedTGtL7CNHe0t2mHtgQlQ3-xwREmSSNYaClAcZpEBV8L7JvMT8JHwdD_a_uSFkDUaP45CAWyL545iZh5gInAdToX6hgt4=@emersion.fr/T/#u)). 

I saw that this was introduced end of last year to fix a regression: https://github.com/wolfpld/tracy/commit/981717f3ef88bfdbd1b29a50fd48b30face251fd. But I can't find details on that regression. Could you link additional info? Maybe there is another workaround? 

Thank you in advance!

**Comment by benblan** [comment]
Hi, I have the same problem on Linux Mint 22.2 for Tracy 0.13.1. But it works with 0.12.2

**Comment by paingineer** [comment]
I had the same issue on Ubuntu 24.04 with 0.13.1. Tag 0.12.2 builds successfully.

**Comment by stgatilov** [comment]
I tried to revert the referenced commit, i.e. replace `wl_display_dispatch_timeout` with `wl_display_dispatch`. The profiler window simply does not display when I launch executable. So I guess it is actually important that this call is non-blocking/peeking.

In the end I enabled GLFW backend by setting `LEGACY` option in CMake. This new binary seems to work fine.
By the way, it uses Wayland as well... I guess because GLFW is built in Wayland / X11 mode.

**Comment by wolfpld** [comment]
> By the way, it uses Wayland as well... I guess because GLFW is built in Wayland / X11 mode.

Historically it was either–or, you had to choose which version you have installed on the system. Now it is dynamic runtime dispatch, I think.

**Comment by Self-Affine** [comment]
I am also getting this build error on Ubuntu 24.04.4 LTS on the master branch

**Comment by wolfpld** [comment]
Can you try if running build artifacts e.g. from https://github.com/wolfpld/tracy/actions/runs/30127029511 gives you a working binary?

**Comment by Self-Affine** [comment]
> Can you try if running build artifacts e.g. from https://github.com/wolfpld/tracy/actions/runs/30127029511 gives you a working binary?

The appimage does not run. It exits with terminal output:

```
Cannot establish wayland display connection!
terminate called without an active exception
Aborted (core dumped)
```

**Comment by wolfpld** [comment]
This issue is about Wayland. Are you running a Wayland compositor? If you are still on X11, then the solution is to use `LEGACY` option, as already answered above.

**Comment by Self-Affine** [comment]
I am using just the default Wayland desktop environment provided by Ubuntu 24.04.4 LTS. I believe the problem is that the version of Wayland (1.22.0-2.1build1) in this Ubuntu distribution is incompatible with the source code for the Tracy profiler server (specifically BackendWayland.cpp).

**Comment by wolfpld** [comment]
> I am using just the default Wayland desktop environment

No, you are not.

---

Anyway, the recently added AppImage script / CI workflow produces a working executable that works on obsolete systems like Ubuntu 24.04, so if anyone is stuck with it for whatever reason, that's your way to go.

**Comment by Self-Affine** [comment]
> > I am using just the default Wayland desktop environment
> 
> No, you are not.
> 
> Anyway, the recently added AppImage script / CI workflow produces a working executable that works on obsolete systems like Ubuntu 24.04, so if anyone is stuck with it for whatever reason, that's your way to go.

My bad, I read a misinformed source that said that Ubuntu 24.04 defaults to Wayland but that is not true in general. I was indeed on x11. I switched to Wayland and the Appimage you provided did run.

**Comment by drsybren** [comment]
> obsolete systems like Ubuntu 24.04

Just posting to let you know there is no upgrade script from Ubuntu 24.04 to 26.04 yet. Because of that, anybody working with the Ubuntu LTS track is still on 24.04. Labeling that as "obsolete" seems a bit unfair.

**Comment by wolfpld** [comment]
Please direct these complaints to Ubuntu issue tracker.
